[package]
version = "1.0.0"
license = "MPL-2.0"
name = "xolborgames/fuzzy-string"
description = """
Fuzzy string algorithms for Roblox.

Includes:
* Levenshtein
* Damerau Levenshtein
"""

realm = "shared"
exclude = [
    ".vscode",
    ".github",

    ".gitignore",

    "aftman.toml",
    "selene.toml",

    "sourcemap.json"
]
include = [
    "src/"
]

registry = "https://github.com/UpliftGames/wally-index"

[dependencies]
